### ISSUE TITLE
Custom textures

### ISSUE THREAD

**Issue by Svetomech** [MainMemory/SADXNoGloss#1]
Doesn't work well with custom textures.
[Left](https://dl.dropboxusercontent.com/u/63791494/temp/d%20%20games%20steamlibrary%20steamapps%20common%20sonic%20adventure%20dx%20tsa2s_us.exe%2010.07.2016%20-%2023.38.28.01.png), [Back](https://dl.dropboxusercontent.com/u/63791494/temp/d%20%20games%20steamlibrary%20steamapps%20common%20sonic%20adventure%20dx%20tsa2s_us.exe%2010.07.2016%20-%2023.38.37.02.png), [Right](https://dl.dropboxusercontent.com/u/63791494/temp/d%20%20games%20steamlibrary%20steamapps%20common%20sonic%20adventure%20dx%20tsa2s_us.exe%2010.07.2016%20-%2023.38.45.03.png), [Forward](https://dl.dropboxusercontent.com/u/63791494/temp/d%20%20games%20steamlibrary%20steamapps%20common%20sonic%20adventure%20dx%20tsa2s_us.exe%2010.07.2016%20-%2023.38.53.04.png).

**Comment by MainMemory** [comment]
This mod doesn't have any effect on textures, so I'm not sure what you want me to do here. If you don't think your textures look good without gloss, then don't use this mod?

**Comment by Svetomech** [comment]
These aren't mine, thanks for being aggressive. 

> This mod doesn't have any effect on textures

Well, I thought it did. Could you at least give me some advice as to how make these textures look better when using your mod instead of shooing me away?

**Comment by michael-fadely** [comment]
Nah, all it does is disable specular lighting. I suppose you could modify the textures to add brighter areas (iirc Sonic's blue shading is just a gradient), but it might not look so great since it can't change direction to match stage lights.

**Comment by MainMemory** [comment]
I wasn't intending to be aggressive, sorry if that's how it came off.

I'm not an artist, so I really don't have any advice for you. I think those textures look fine, but if you really think the gloss makes them look better, I guess you'd need some kind of blacklist/whitelist system.

**Comment by Svetomech** [comment]
> but it might not look so great since it can't change direction to match stage lights.

But the original textures don't have this "worn out" look for some reason when using the mod. Am I missing something?

> sorry if that's how it came off

It's okay. And I don't think the gloss makes them look better. I don't reckon the gloss used in SADX makes anything look better, for that matter (:

@MainMemory, @SonicFreak94, I edited the comment.

**Comment by Svetomech** [comment]
Sorry, forgot to mention: I am talking about Sonic textures.
