### ISSUE TITLE
Dosent work in Updated Modloader

### ISSUE THREAD

**Issue by RinMaru** [MainMemory/SADXNoGloss#2]
Ive tried loading it last and loading it first but nothing works im using it with DC mods

**Comment by MainMemory** [comment]
Works fine for me. Does the mod loader's log say anything?

**Comment by RinMaru** [comment]
DisableCDCheck=True
UseCustomResolution=True
HorizontalResolution=1920
VerticalResolution=1080
ScaleHud=True
PauseWhenInactive=False
StretchFullscreen=False
ScreenNum=0
WindowWidth=320
WindowHeight=240
Mod1=SADXStyleWater
Mod2=ADX Music & Voice
Mod3=Input-Mod
Mod4=Smooth-Cam
Mod5=Pause-Hide
Mod6=Super Sonic Mod
Mod7=DC_Bosses
Mod8=DC_Branding
Mod9=DC_Casinopolis
Mod10=DC_EggCarrier
Mod11=DC_EmeraldCoast
Mod12=DC_FinalEgg
Mod13=DC_HotShelter
Mod14=DC_IceCap
Mod15=DC_LostWorld
Mod16=DC_MysticRuins
Mod17=DC_Past
Mod18=DC_RedMountain
Mod19=DC_SkyDeck
Mod20=DC_SpeedHighway
Mod21=DC_StationSquare
Mod22=DC_SubGames
Mod23=DC_TornadoModels
Mod24=DC_TwinklePark
Mod25=DC_WindyValley
Mod26=DC_EnvMaps
Mod27=DC~ HD GUI+CharTextures+Voices
Mod28=TrainDaytime
Mod29=DC_Lighting
Mod30=NoGloss
Code1=Disable scrolling on title screen
Code2=Disable Sonic Team Logo

Is this the log?

**Comment by MainMemory** [comment]
No. In the mod manager's Options tab, check the "File" option under "Debug Messages". Then after starting the game, go to mods\SADXModLoader.log.

**Comment by RinMaru** [comment]
will do brb

**Comment by RinMaru** [comment]
[SADXModLoader.zip](https://github.com/MainMemory/SADXNoGloss/files/778542/SADXModLoader.zip)

**Comment by MainMemory** [comment]
Actually, from the INI data you posted, you've got the DC lighting mod on, which kind of makes the NoGloss mod entirely pointless, as it completely changes the way lighting is calculated.

**Comment by RinMaru** [comment]
oh so thats why lol ^\\^ thanks for your help ^^
